### ISSUE TITLE
Default to 3 or 4 fingers for workspace gestures

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os-patches#142]
## Problem

Sometimes I accidentally get my pinky on the trackpad and three-finger gestures don't trigger. Or I just forget that it's only 3 fingers and try using all 4.

## Proposal

We could accept three or four fingers for workspace gestures in our config by default. Alternatively, Touchégg could interpret gestures with four fingers and count them as three-finger gestures if there are no matching four-finger gestures configured.

## Prior Art

It looks like this is what macOS does ootb, at least on @katiemkblaede's MacBook Pro.

**Comment by JoseExposito** [comment]
As you mention, we can add an extra config to switch workspaces with 3 or 4 fingers in order to fix this: https://github.com/elementary/os-patches/pull/141/commits/de162bc49b280dc8b70b88d13060a3dbc7307e5e

IMHO, it'll be nice if is this could be configured in Settings > Mouse & Touchpad. On big touchpads using 3 fingers feels awkward and, using 4 fingers to change workspaces allows to use 3 fingers for something else.
I don't know if you have plans for this, but I can create a PR.

> Alternatively, Touchégg could interpret gestures with four fingers and count them as three-finger gestures if there are no matching four-finger gestures configured.

People tend to configure the most incredible actions for 3/4 swipes you can think of :laughing: I don't think this is something that will work most of the time.

**Comment by danrabbit** [comment]
This is now fixed in the conf file we ship. Thanks José!

There's an issue report regarding gestures configuration (complete with LOTS of opinions) here: https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/16
