### ISSUE TITLE
Using apt to install packages like chromium installs snapd and the package as a snap

### ISSUE THREAD

**Issue by ibrahimrahman** [elementary/os-patches#176]
## What Happened

Hello, I am not sure if this is the correct place to file this issue. 

As the title suggests, installing chromium-browser using apt first installs snapd and then installs it as a snap package. This is due to Ubuntu's recent push for snaps, and while I am aware that the recommended method for installing apps is flatpak, it would still be nice to make sure that the system doesn't do this. I am certain this affects some other packages as well.

## Expected Behavior

The .deb version should have been installed instead

## Steps to Reproduce

1. Run `sudo apt install chromium-browser`

## Platform Information

elementary OS 6 Early Access

**Comment by danrabbit** [comment]
Since the recommended method for installing apps is via Flatpak and this package is coming from Ubuntu, and we no longer show Ubuntu packages in AppCenter, I'm going to close this as "Out of scope". The only way to fix this would be to start packaging these apps as debs ourselves, which we're not going to do for the same reasons that Ubuntu doesn't want to do it anymore.
