### ISSUE TITLE
Port all os-patches to git and github

### ISSUE THREAD

**Issue by codygarver** [elementary/os-patches#3]
Right now they're all hosted on launchpad and bzr.

**Comment by codygarver** [comment]
Basically all done, some old recipe series aren't ported but that can be tracked here: https://github.com/orgs/elementary/projects/14

**Comment by waldyrious** [comment]
@codygarver AFAIK projects don't allow "watching", i.e. getting notifications for updates; i.e. there's no way to subscribe to all issues/cards managed in the project, and while issues can be manually subscribed to, cards can't.

This means that people who are interested in tracking specific issues, and hopefully help out where they can, end up without a way to get notifications of activity.

Please consider reopening this or creating issues for the missing items (e.g. converting the cards in that project to issues, so that they can be subscribed to).
