### ISSUE TITLE
Diff code highlight highlights only in high contrast theme

### ISSUE THREAD

**Issue by marmeladapk** [elementary/os-patches#66]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Diff code highlight highlights only in high contrast theme.

### To Reproduce
1. Open any patch file generated by git (or paste output of diff command)
2. Select diff code highlight
3. Change themes in options

### Expected behavior

Highlight should work with all themes.

### Screenshots or screen recordings

![Zrzut ekranu z 2019-09-30 18 20 05](https://user-images.githubusercontent.com/24512604/65897218-1b669380-e3af-11e9-884d-954427a2dbe6.png)
![Zrzut ekranu z 2019-09-30 18 20 15](https://user-images.githubusercontent.com/24512604/65897219-1bff2a00-e3af-11e9-8046-84d06145bb1b.png)
![Zrzut ekranu z 2019-09-30 18 20 31](https://user-images.githubusercontent.com/24512604/65897220-1bff2a00-e3af-11e9-9415-abd9678930b1.png)
## Platform Information

![Zrzut ekranu z 2019-09-30 18 24 03](https://user-images.githubusercontent.com/24512604/65897390-7dbf9400-e3af-11e9-9578-ee3eb318fc37.png)
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by ryonakano** [comment]
Closing because Code now uses elementary-light and elementary-dark styles instead of solarized ones, which can highlight diffs nicely:

![スクリーンショット 2024-09-16 09 39 40](https://github.com/user-attachments/assets/d6b6f2af-7cd7-4256-be60-216279b7e74e)
![スクリーンショット 2024-09-16 09 39 43](https://github.com/user-attachments/assets/95fa83c1-6856-434a-8cd2-5a6072d1b526)

You'll still face this behavior if you set `solarized-light` or `solarized-dark` to the `/io/elementary/code/settings/style-scheme` gschema key directly through gsettings command or dconf-editor, but that operation is not recommended/supported officially. Also, the solarized themes comes with gtksourceview >= 5.5.0 [has been updated to highlight diffs](https://gitlab.gnome.org/GNOME/gtksourceview/-/commit/1e14c456d2002e48169dfe32a247601bd72c923b), so this corner case should be fixed anyways once Code migrate to gtksourceview 5 (which means migration to GTK 4).
